---
# This file tells https://pre-commit.com/
# which hooks are provided by this repo
# for use by other git repos.

- id: novalid-yaml-fmt
  name: Format YAML files
  description: Format YAML files
  entry: "novalid-yaml-fmt"
  args: [ -w ]
  language: script
  files: \.(yaml|yaml.gotmpl)$
  types:
    - file
