---

repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-merge-conflict

  - repo: https://github.com/pycqa/pylint
    rev: v2.15.4
    hooks:
    -   id: pylint
        args:
        - --max-line-length=100
        - --ignore-imports=yes
